### ISSUE TITLE
Add Mongoose User Schema [5]

### ISSUE THREAD

**Issue by wacwestley30** [wacwestley30/study-group-finder-app#1]
## User Schema
- user should have a first and last name
- user should have username
- user should have email
- user should have password
- user needs a university
- user needs a major
- user needs year (year 1, 2, 3 etc.)
- user needs Groups 

## Technology
- Mongoose Schema - Apollo will consume schema
- bycrypt - encrypt password

# Definition of Done
- Schema is tested
- Schema has encrypted password
- Schema returns all fields
  - subdoc for Groups

**Comment by lessGeaux** [comment]
- [ ] @noodle77, _rename the branch_ attached to this issue to `001-add-mongoose-user-model`[^1]

![Image](https://github.com/wacwestley30/study-group-finder-app/assets/100882971/eeed8658-fdcf-4e9c-9ea8-79a897b6a3ad)

[^1]: [see instructions in my comment to @bcgosselin ](https://github.com/wacwestley30/study-group-finder-app/issues/5#issuecomment-2148282101); [see rationale](https://medium.com/@abhay.pixolo/naming-conventions-for-git-branches-a-cheatsheet-8549feca2534)
