### ISSUE TITLE
Register A New User (Server) [8]

### ISSUE THREAD

**Issue by wacwestley30** [wacwestley30/study-group-finder-app#3]
## Register A User
- Required Fields:
  - Email
  - Username
  - Password

## Technology
- Apollo / GraphQL
  - Create a new Document via transformation (Mutation)

# Definition of Done
- new User Document is added to User Collection
- JWT is signed to the new User
- Password is encrypted by bycrpt
- Unique `_id` is generated

**Comment by lessGeaux** [comment]
- [x] _add branch_ to this ticket
- [ ] _rename the branch_ attached to this ticket to `003-register-a-new-user`[^1]

@llYakll  [see my comment to @bcgosselin for git steps to do this](https://github.com/wacwestley30/study-group-finder-app/issues/5#issuecomment-2148282101) about how to rename your branch name.

[^1]: _rationale_: clean branches for future employers
