### ISSUE TITLE
Seed [3]

### ISSUE THREAD

**Issue by bcgosselin** [wacwestley30/study-group-finder-app#30]
# Definition of Done:
- 10 groups revolving around 5 subjects
  - or as many will fill page (cosmetic)
- 5 random users in each group
- `npm run seed` should clear DB then reseed
  - all users should be cleared
  - all groups should be cleared

**Comment by bcgosselin** [comment]
created seed and correlating seed files to input starter data into the studdy database.

**Comment by wacwestley30** [comment]
Updated to properly seed the Groups Users are associated with.
