### ISSUE TITLE
Group Page [3]

### ISSUE THREAD

**Issue by bcgosselin** [wacwestley30/study-group-finder-app#32]
# Definition of Done
- Update React Router in `main.jsx`
  - page needs to be within a container (bulma)
- Display details of Group Model
- IF logged in can join group
  - group mutation (see `JOIN_GROUP`)

**Comment by wacwestley30** [comment]
- Currently in main you have to manually navigate to `/groups`
- GroupsPage is not set up in Router correctly
- GroupDetails is not set up in Router correctly
- Proper testing needed before pushing up
