### ISSUE TITLE
Login Modal [3]

### ISSUE THREAD

**Issue by wacwestley30** [wacwestley30/study-group-finder-app#5]
## Login Modal
Clicking into a Login button opens a Modal for logging in

## Technologies
- React Router

# Definition of Done
- Modal needs:
  - input for Username
  - input for Password
- Register Button

**Comment by lessGeaux** [comment]
@bcgosselin, I have added the branch to this ticket!
- [x] _attach_ **related branch** to this **issue**
- [ ] _rename_ your **local branch** for this ticket to `005-login-modal`

_rename_ you **local branch**:
`git branch -m [old_branch_name] [new_branch_name]`

**WARNING: be sure to not delete your work -- pay attention to the commands!**
_rename_ your **remote branch** (on git):
<img width="766" alt="Screenshot 2024-06-04 at 1 39 02 PM" src="https://github.com/wacwestley30/study-group-finder-app/assets/100882971/94b44957-d4db-43e9-9505-8faf8e9d4b49">
